"""Idempotent Hermes cron registration for the heartbeat (roadmap 1.1, HLA D1).

``register(ctx)`` runs on **every** Hermes start / plugin load, so registering
the cron job unconditionally would pile up duplicate ``lifemodel-heartbeat``
jobs. This module owns that registration and makes it **idempotent**: it checks
for an existing job by stable name and creates one only if absent, while always
refreshing the launcher shim so a moved plugin still resolves.

**The launcher shim.** Hermes runs a cron ``--script`` with ``sys.executable``
(its own interpreter) and resolves the script path under
``<HERMES_HOME>/scripts/`` (``cron/scheduler.py:_run_job_script``). The
``lifemodel`` package is *not* on Hermes' ``sys.path`` there, so we drop a tiny
generated shim into that scripts dir that inserts the plugin's ``src`` dir onto
``sys.path`` and then runs :func:`lifemodel.tick.main`. The shim is the only
supported way to bridge "Hermes runs the file" and "the file imports our
package" without vendoring anything into Hermes' venv.

**Dependency injection.** The Hermes cron API (``create_job`` / ``list_jobs``)
is passed in as plain callables, so the idempotency logic is unit-tested with
fakes and never imports Hermes; :func:`register_heartbeat` is the thin real-host
wrapper that imports ``cron.jobs`` and delegates. Stdlib only in the tested core.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any

from .logging import EventLogger, get_logger

#: Stable job name — the idempotency key. One heartbeat per profile (HLA D1).
HEARTBEAT_JOB_NAME = "lifemodel-heartbeat"
#: Every-minute pulse; 60s is Hermes' cron floor (``parse_duration``, HLA D1).
HEARTBEAT_SCHEDULE = "every 1m"
#: Filename of the generated launcher shim under ``<HERMES_HOME>/scripts/``.
SHIM_FILENAME = "lifemodel_heartbeat.py"
#: Subdir of the profile home where Hermes resolves cron ``--script`` paths.
SCRIPTS_DIR_NAME = "scripts"
#: Woken-agent prompt. Unused in 1.1 (the gate never wakes the agent); a real
#: proactive prompt is 1.4. Kept short and text-only.
_HEARTBEAT_PROMPT = (
    "lifemodel heartbeat: the being's pressure crossed its threshold. "
    "Consider whether to reach out; keep it brief and text-only."
)

#: Structural types for the slice of the Hermes cron API we use, so the tested
#: core takes injected callables (real or fake) instead of importing ``cron``.
CreateJob = Callable[..., dict[str, Any]]
ListJobs = Callable[..., list[dict[str, Any]]]

_SHIM_TEMPLATE = """\
#!/usr/bin/env python3
# AUTO-GENERATED by hermes-lifemodel register() — do not edit by hand.
# Thin launcher for the cron heartbeat: put the lifemodel plugin package on
# sys.path (Hermes runs this with its own interpreter, which does not have the
# plugin installed), then run exactly one tick. The tick prints a single JSON
# wake-gate line to stdout; all logs go to stderr.
import sys

sys.path.insert(0, {src_dir!r})

from lifemodel.tick import main

raise SystemExit(main())
"""


def render_shim(src_dir: Path) -> str:
    """Return the launcher-shim source with *src_dir* baked in as the import path."""
    return _SHIM_TEMPLATE.format(src_dir=str(src_dir))


def write_shim(home: Path, src_dir: Path) -> Path:
    """Write the launcher shim under ``<home>/scripts/`` and return its path.

    Idempotent: rewrites only when the content differs (e.g. the plugin moved),
    so repeated plugin loads leave the file byte-identical. Creates the scripts
    dir on demand — Hermes also does, but the shim must exist before the first
    tick fires.
    """
    scripts_dir = home / SCRIPTS_DIR_NAME
    scripts_dir.mkdir(parents=True, exist_ok=True)
    shim_path = scripts_dir / SHIM_FILENAME
    content = render_shim(src_dir)
    if not shim_path.exists() or shim_path.read_text(encoding="utf-8") != content:
        shim_path.write_text(content, encoding="utf-8")
    return shim_path


def _existing_heartbeat(list_jobs: ListJobs) -> dict[str, Any] | None:
    """Return the already-registered heartbeat job, or ``None`` (incl. disabled).

    Matches on the stable :data:`HEARTBEAT_JOB_NAME` and includes disabled jobs
    so a paused heartbeat is still recognised — we must not silently create a
    second one alongside it.
    """
    for job in list_jobs(include_disabled=True):
        if job.get("name") == HEARTBEAT_JOB_NAME:
            return job
    return None


def ensure_heartbeat_job(
    *,
    home: Path,
    src_dir: Path,
    create_job: CreateJob,
    list_jobs: ListJobs,
    logger: EventLogger | None = None,
    deliver: str = "local",
) -> dict[str, Any]:
    """Ensure exactly one heartbeat cron job exists; return it (idempotent).

    Always refreshes the launcher shim, then registers the cron job **only if**
    no job with the stable name already exists — so calling this on every plugin
    load never duplicates the heartbeat. The job carries both a ``script`` (our
    tick) and ``no_agent=False``, so the scheduler runs the script first and can
    wake the agent later (1.3+) when the wake gate flips; today the gate is
    always ``wakeAgent=false`` (zero LLM).
    """
    log = logger or get_logger("lifemodel.heartbeat")
    write_shim(home, src_dir)

    existing = _existing_heartbeat(list_jobs)
    if existing is not None:
        log.info("heartbeat_exists", job_id=existing.get("id"), name=HEARTBEAT_JOB_NAME)
        return existing

    job = create_job(
        _HEARTBEAT_PROMPT,
        HEARTBEAT_SCHEDULE,
        name=HEARTBEAT_JOB_NAME,
        script=SHIM_FILENAME,
        no_agent=False,
        deliver=deliver,
    )
    log.info("heartbeat_registered", job_id=job.get("id"), name=HEARTBEAT_JOB_NAME)
    return job


def register_heartbeat(home: Path, src_dir: Path, *, logger: EventLogger | None = None) -> None:
    """Real-host wrapper: import the Hermes cron API and ensure the heartbeat.

    The Hermes touchpoint — imported lazily so this module stays importable off
    host. Called from :func:`lifemodel.register`; on a host without the cron API
    the ``ImportError`` propagates to that best-effort caller (plugin load must
    survive a cron-registration failure).
    """
    from cron.jobs import create_job, list_jobs

    ensure_heartbeat_job(
        home=home,
        src_dir=src_dir,
        create_job=create_job,
        list_jobs=list_jobs,
        logger=logger,
    )
